import React from 'react';

interface DocumentPreviewProps {
  content: string;
  title: string;
}

const DocumentPreview: React.FC<DocumentPreviewProps> = ({ content, title }) => {
  // Simple markdown to HTML converter
  const renderMarkdown = (markdown: string) => {
    let html = markdown;

    // Convert headers
    html = html.replace(/^### (.*$)/gim, '<h3 class="text-lg font-semibold text-gray-900 mt-6 mb-3">$1</h3>');
    html = html.replace(/^## (.*$)/gim, '<h2 class="text-xl font-semibold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">$1</h2>');
    html = html.replace(/^# (.*$)/gim, '<h1 class="text-2xl font-bold text-gray-900 mt-4 mb-6">$1</h1>');

    // Convert bold
    html = html.replace(/\*\*(.*?)\*\*/gim, '<strong class="font-semibold text-gray-900">$1</strong>');

    // Convert italic
    html = html.replace(/\*(.*?)\*/gim, '<em class="italic">$1</em>');

    // Convert lists
    html = html.replace(/^\- (.*$)/gim, '<li class="ml-6 mb-2">• $1</li>');
    html = html.replace(/^\d+\. (.*$)/gim, '<li class="ml-6 mb-2 list-decimal">$1</li>');

    // Convert tables (basic support)
    html = html.replace(/\|(.+)\|/g, (match) => {
      const cells = match.split('|').filter(cell => cell.trim());
      const cellsHtml = cells.map(cell => 
        `<td class="border border-gray-300 px-4 py-2">${cell.trim()}</td>`
      ).join('');
      return `<tr>${cellsHtml}</tr>`;
    });

    // Wrap tables
    html = html.replace(/(<tr>.*<\/tr>\s*)+/gim, '<table class="min-w-full border-collapse border border-gray-300 my-4">$&</table>');

    // Convert line breaks
    html = html.replace(/\n\n/g, '</p><p class="mb-4 text-gray-700 leading-relaxed">');
    html = html.replace(/\n/g, '<br/>');

    // Wrap in paragraph
    html = '<p class="mb-4 text-gray-700 leading-relaxed">' + html + '</p>';

    // Convert horizontal rules
    html = html.replace(/^---$/gim, '<hr class="my-8 border-t border-gray-300"/>');

    return html;
  };

  return (
    <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8 max-w-4xl mx-auto">
      {/* Document Header */}
      <div className="mb-8 pb-6 border-b-2 border-gray-900">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">{title}</h1>
        <p className="text-sm text-gray-500">Generated Document</p>
      </div>

      {/* Document Content */}
      <div 
        className="prose prose-sm max-w-none"
        dangerouslySetInnerHTML={{ __html: renderMarkdown(content) }}
      />

      {/* Document Footer */}
      <div className="mt-12 pt-6 border-t border-gray-300 text-xs text-gray-500">
        <p>This document was generated by AI DocWriter</p>
      </div>
    </div>
  );
};

export default DocumentPreview;
